# Generated by Django 5.2.14 on 2026-05-12 04:46

import approvals.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(default=approvals.models.generate_request_id, max_length=50, unique=True)),
                ('document_name', models.CharField(max_length=255)),
                ('document_description', models.TextField(blank=True)),
                ('request_message', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('status', models.CharField(choices=[('PENDING_LOWER', 'Pending Lower'), ('PENDING_MIDDLE', 'Pending Middle'), ('PENDING_HIGHER', 'Pending Higher'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_LOWER', max_length=20)),
                ('lower_approved', models.BooleanField(default=False)),
                ('middle_approved', models.BooleanField(default=False)),
                ('higher_approved', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FORWARDED', 'Forwarded')], max_length=10)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.approvalrequest')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'User'), ('LOWER', 'Lower Level Approver'), ('MIDDLE', 'Middle Level Approver'), ('HIGHER', 'Higher Level Approver')], default='USER', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
